language: ruby
rvm:
- 2.4.1
install:
- "./bin/setup"
script:
- bundle exec jekyll build --trace
- bundle exec htmlproofer ./_site --only-4xx --allow-hash-href
after_success:
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && "./bin/automated"
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - USERNAME: aa1874
  - EMAIL: gibranalnn@outlook.com
  - secure: jpmW9HGkT0JIVxax/Zl1wASX09tw0od+3Bg8XfBboBY6iB93cw1ufJspIQlF0ui2LNl84BQxgSkA5Ze3U5YYAZ3M++vSeRIfUmHvyCEvx3nLrO5nhiBTvSs7IF4WD0gD5sC1SfE4rl1U/DKg5eymK4mSo7xM5AnqhHfGWQWEuDyiRl9Zqbz0H+UtGvCbiobbJZDvXbcAuziHURzTac4iQqUxkm9FrgEu+gDrZ76T14brRGpdFCIS2ZomHCE5VJCaYxXKCwQ4GUkaQTK31NAjSgsen/9+0VsKMd0Y7C5ug/xVtjO28v2pC00XfxjhbUd0Zptd2jizg6+RO/Th+j6fa30mQO4sjpkf2eqcOGUsI9ZUwMnCHZisDV/Hy0SJjXZFXl8+7WsD895vZ9Dko6xtCDHC9hqQA7GHUvUPdAlOCzKU7VBvwv8PYqePuV/VfnkedOkpjakVFpMHFEJTyKTTBLc1RaIP8ZuPQa+OW7tWDx5VQxtaZcOWpofKcdk14kd2W8fU9zNbTS7BSrTM/2OKS6Irq7VAe8aqomUEfbXbU5wSY9lKITHcJxvpBNp9fPMfyj9rquKOY1FISFixiy0q+VjZBt9mc6rjj7FCLz6O9D24Rq4xNHonJjFpJQEkdECPQRLDjBrwSrXUJ7OO6VP8szTYTmnCp14FroiUhRZREbk=
